#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
xrandr --output DP-1-2 --auto --left-of eDP-1-1 --auto &

# Multiple Monitors

if type "xrandr"; then
  for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
    MONITOR=$m polybar --reload example &
  done
else
  polybar --reload example &
fi

#polybar example
bing.sh
picom -b --experimental-backends
xrdb -merge ~/.Xresources
urxvtd -o -q -f


bspc monitor -d I II III IV V

bspc config border_width         2
bspc config window_gap          15
bspc config focus_follows_pointer true
bspc config presel_feedback_color "#81a1c1"

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# border colors
bspc config focused_border_color "#a3be8c"
bspc config normal_border_color  "#2e3440"
bspc config active_border_color  "#ebcb8b"

xsetroot -cursor_name left_ptr


