#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &

#polybar example
picom -b --experimental-backends
xrdb -merge ~/.Xresources
urxvtd -o -q -f
./.screenlayout/screens.sh
bing.sh

# Multiple Monitors

if type "xrandr"; then
  for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
    MONITOR=$m polybar --reload example &
  done
else
  polybar --reload example &
fi

polybar --reload example &

bspc monitor eDP-1 -d         
bspc monitor DP-2  -d         
bspc monitor DP-4  -d         
bspc monitor eDP-1-1 -d         
bspc monitor DP-1-2  -d         
bspc monitor DP-1-4 -d          


#bspc monitor DP-1-2  -d         



##Then, create workspaces on all monitors
#I=1
#M=$(bspc query -M | wc -l)
#if [[ "$M" == 1 ]]; then
#  bspc monitor -d 1 2 3 4 5 6 7 8 9 10 11 12
#elif [[ "$M" == 2 ]]; then
#  bspc monitor $(bspc query -M | awk NR==1) -d 1 2 3 4 5 6 7 
#  bspc monitor $(bspc query -M | awk NR==2) -d 8 9 10 11 12 13 14
#elif [[ "$M" == 3 ]]; then
#  bspc monitor $(bspc query -M | awk NR==1) -d 1 2 3 4
#  bspc monitor $(bspc query -M | awk NR==2) -d 5 6 7 8
#  bspc monitor $(bspc query -M | awk NR==3) -d 9 10 11
#elif [[ "$M" == 4 ]]; then
#  bspc monitor $(bspc query -M | awk NR==1) -d 1 2 3
#  bspc monitor $(bspc query -M | awk NR==2) -d 4 5 6
#  bspc monitor $(bspc query -M | awk NR==3) -d 7 8 9
#  bspc monitor $(bspc query -M | awk NR==4) -d 10 11
#elif [[ "$M" == 5 ]]; then
#  bspc monitor $(bspc query -M | awk NR==1) -d 1 2 3
#  bspc monitor $(bspc query -M | awk NR==2) -d 4 5
#  bspc monitor $(bspc query -M | awk NR==3) -d 6 7
#  bspc monitor $(bspc query -M | awk NR==4) -d 8 9
#  bspc monitor $(bspc query -M | awk NR==5) -d 10 11
#else
#  for monitor in $(bspc query -M); do
#    bspc monitor $monitor \
#      -n "$I" \
#      -d $I/{a,b,c}
#    let I++
#    done
#fi


bspc config border_width      2
bspc config window_gap       15%
bspc config top_padding     0

bspc config focus_follows_pointer true
bspc config presel_feedback_color "#81a1c1"

bspc config split_ratio          0.5
#bspc config borderless_monocle   true
#bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

# border colors
bspc config focused_border_color "#92b5d9"
bspc config normal_border_color  "#2e3440"
bspc config active_border_color  "#bf616a"

xsetroot -cursor_name left_ptr


